import type { Metadata } from "next";
import { Inter, Montserrat, Figtree } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '900'],
  variable: '--font-figtree',
});
// Load Inter font
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600'],
  variable: '--font-inter',
});

// Load Montserrat font
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '900'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${figtree.variable} ${montserrat.variable} antialiased`}
      >
        <Header />
        <main className="min-h-screen pt-[var(--header-height)] bg-it-dark-900 ">
          <div className="py-8">

            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
