const PortfolioAPI = {
    page: 1,
    totalPage: 3,
    data: {
        portfolio: [
            {
                id: 1,
                title: 'Raush',
                slug: 'raush',
                startDate: '2022-01-21',
                endDate: '2022-07-21',
                isWorking: true,
                hasDesign: false,
                workType: 'Part Time',
                location: 'Remote',
                description: 'This is a description',
                sideProject: false,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658408288/Portfolio/raush.png',
                ],
            },
            {
                id: 2,
                title: 'Banana Boyz Club',
                slug: 'banana-boyz-club',
                startDate: '2022-01-21',
                endDate: '2022-07-21',
                isWorking: false,
                hasDesign: true,
                workType: 'Contract',
                location: 'Remote',
                description: 'This is a description',
                sideProject: false,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658417518/Portfolio/Banana_Boyz_Club_nphhr8.png',
                ],
            },
            {
                id: 3,
                title: 'Protoconn',
                slug: 'protoconn',
                startDate: '2022-02-01',
                endDate: '2022-05-31',
                isWorking: false,
                hasDesign: true,
                workType: 'Contract',
                location: 'Remote',
                description: 'This is a description',
                sideProject: false,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658408288/Portfolio/raush.png',
                ],
            },
            {
                id: 4,
                title: 'Think Studio',
                slug: 'think-studio',
                startDate: '2021-02-01',
                endDate: '2021-05-31',
                isWorking: false,
                hasDesign: false,
                workType: 'Contract',
                location: 'Remote',
                description: 'This is a description',
                sideProject: false,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658408288/Portfolio/raush.png',
                ],
            },
            {
                id: 5,
                title: 'WilsonH',
                slug: 'wilsonh',
                startDate: '2021-02-01',
                endDate: '2021-05-31',
                isWorking: false,
                hasDesign: false,
                workType: 'Contract',
                location: 'Remote',
                description: 'This is a description',
                sideProject: false,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658408288/Portfolio/raush.png',
                ],
            },
            {
                id: 6,
                title: 'Rehash LTD',
                slug: 'rehash-ltd',
                startDate: '2021-02-01',
                endDate: '2021-05-31',
                isWorking: false,
                hasDesign: true,
                workType: 'Contract',
                location: 'Remote',
                description: 'This is a description',
                sideProject: false,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658408288/Portfolio/raush.png',
                ],
            },
            {
                id: 7,
                title: 'Movie App',
                slug: 'movie-app',
                startDate: '2021-02-01',
                endDate: '2021-05-31',
                isWorking: false,
                hasDesign: true,
                workType: 'Side Project',
                location: 'Remote',
                description: 'This is a description',
                sideProject: true,
                images: [
                    'https://res.cloudinary.com/dv7g8veki/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1658408288/Portfolio/raush.png',
                ],
            },
        ],
    },
};

export { PortfolioAPI };
