name: Lint
on: [push, pull_request]

jobs:
  run-linters:
    name: Yarn Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repo
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1
        with:
           node-version: '16.x'

      - name: Install Next.js Dependencies
        run: yarn install --frozen-lockfile
      # Run Lint
      - name: Run Lint
        run: yarn lint
      # Run build
      - name: Yarn build
        run: yarn build
