name: Lint
on: [pull_request]

jobs:
  run-linters:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm 
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Next.js Dependencies
        run: pnpm install --frozen-lockfile
      # Run Lint
      - name: Run Lint
        run: pnpm lint
      # Run build
      - name: pnpm build
        run: pnpm build
