name: Lint
on: push

jobs:
  run-linters:
    name: Yarn Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repo
        uses: actions/checkout@v3 
      - name: Setup Node.js
        uses: actions/setup-nodejs@v1
        with:
          node-version: 16
      - name: Setup yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'

      - name: Install Next.js Dependencies
        run: npm ci
      # Run Lint
      - name: Run Lint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
