name: Lint and Build

on: [pull_request]

jobs:
  run-linters:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Next.js Dependencies with Bun
        run: bun install --frozen-lockfile

      - name: Run Lint with Bun
        run: bun run lint

      - name: Build with Bun
        run: bun run build
